<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFramework>net8.0-android</TargetFramework>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseMaui>true</UseMaui>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Maui2JS.Core\Maui2JS.Core.csproj" />
	</ItemGroup>
</Project>